name: SFI Docker Image Build and Push

on:
  push:
    branches: [ main, alpha, beta, test, latest-np ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Branch Info   
        run: |
          echo "Branch Name: ${{ steps.branch-name.outputs.current_branch }}"
          echo "Is Default Branch: ${{ steps.branch-name.outputs.is_default }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Latest
        uses: docker/build-push-action@v2
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }} 
        with:
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vlocity_sfdx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sfdx_vlocity_java:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sfdx_vlocity_puppeteer:latest
          secrets: |
            "SF_GITHUB_PASS=${{ secrets.SF_GITHUB_PASS }}"
      -
        name: Build and push - Branch Name
        uses: docker/build-push-action@v2
        if: ${{ steps.branch-name.outputs.current_branch != 'main' }} 
        with:
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vlocity_sfdx:${{ steps.branch-name.outputs.current_branch }}
          secrets: |
            "SF_GITHUB_PASS=${{ secrets.SF_GITHUB_PASS }}"